id: I4F38822F
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:45:08.816346
last_modified: 2023-02-09 14:45:08.816442
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: zh
bases:
  '9694':
    base_file: 9694.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
